### ISSUE TITLE
Corner stairs state not showing correctly in schematic placement

### ISSUE THREAD

**Issue by JesperKnez** [sakura-ryoko/litematica#98] opened 2024-11-15 07:20 UTC
I have built a gold farm on a survival server. I wanted to rebuild it on a different server, so i made a schematic out of it.

However notice how the stairs showed are not in the correct form:

![2024-11-15_08 16 44](https://github.com/user-attachments/assets/08a2e02b-f137-40ec-955b-f0965c4f5262)
![2024-11-15_08 16 56](https://github.com/user-attachments/assets/6b1d018d-66ae-4c93-99a2-e4f48960eeeb)

I think this is a bug as state on all other blocks is saved fine (trapdoors etc)

version: litematica-fabric-1.21.3-0.20.0-sakura.3.jar

**Comment by sakura-ryoko** [comment] 2024-12-17 20:02
Does this problem still occur in sakura.7 / sakura.8 ?

**Comment by sakura-ryoko** [comment] 2024-12-19 00:36
To be fair, I needed more information on this problem.  In order to Reproduce it, the Schematic needs to be in `Mirror: FRONT_BACK` mode in order to reproduce it.

![2024-12-18_19 34 22](https://github.com/user-attachments/assets/fc2e3c0c-d9aa-493b-9ccd-f690f0587187)

**Comment by sakura-ryoko** [comment] 2024-12-19 02:27
I found a fix.  It's not a "pretty" fix code wise, but it works.  Fix will be in sakura.9+

**Comment by sakura-ryoko** [comment] 2024-12-19 03:03
Scratch that.  This "fix" won't cut it because something is breaking the stairs' "Mirror / Rotation" depending on material type...
This is cursed to fix.

**Closed as completed** 2024-12-19 05:00 UTC
Labels: bug, fixed
